<?php

/**
 * TMongoScaffoldInput class file.
 *
 * @author Brad Anderson <belisoful@icloud.com>
 * @link https://github.com/pradosoft/prado
 * @license https://github.com/pradosoft/prado/blob/master/LICENSE
 */

namespace Prado\Data\ActiveRecord\Scaffold\InputBuilder;

use Prado\TPropertyValue;
use Prado\Web\UI\WebControls\TCheckBox;
use Prado\Web\UI\WebControls\TDataTypeValidator;
use Prado\Web\UI\WebControls\TDatePicker;
use Prado\Web\UI\WebControls\TDatePickerInputMode;
use Prado\Web\UI\WebControls\TRequiredFieldValidator;
use Prado\Web\UI\WebControls\TTextBox;
use Prado\Web\UI\WebControls\TTextBoxMode;
use Prado\Web\UI\WebControls\TValidationDataType;
use Prado\Web\UI\WebControls\TValidatorDisplayStyle;

/**
 * TMongoScaffoldInput class.
 *
 * Maps MongoDB BSON field types (from {@see \Prado\Data\Common\Mongo\TMongoFieldInfo})
 * to appropriate Prado scaffold input controls.
 *
 * This class is the MongoDB analogue of {@see TMysqlScaffoldInput},
 * {@see TFirebirdScaffoldInput}, etc.  Because MongoDB is schemaless and uses
 * BSON types rather than SQL column types, `createControl` and `getControlValue`
 * branch on {@see \Prado\Data\Common\Mongo\TMongoFieldInfo::getBsonType} rather
 * than a SQL `DbType`.
 *
 * The `$column` argument throughout this class is expected to be a
 * {@see \Prado\Data\Common\Mongo\TMongoFieldInfo} instance.
 *
 * @author Brad Anderson <belisoful@icloud.com>
 * @since 4.3.3
 */
class TMongoScaffoldInput extends TScaffoldInputBase
{
	/**
	 * Creates the appropriate input control for a MongoDB field.
	 *
	 * @param mixed $container the container control.
	 * @param \Prado\Data\Common\Mongo\TMongoFieldInfo $column the field metadata.
	 * @param mixed $record the active record instance.
	 * @return mixed the created control.
	 */
	protected function createControl($container, $column, $record)
	{
		switch (strtolower($column->getBsonType())) {
			case 'bool':
			case 'boolean':
				return $this->createBooleanControl($container, $column, $record);
			case 'date':
				return $this->createDateTimeControl($container, $column, $record);
			case 'int':
			case 'long':
			case 'timestamp':
				return $this->createIntegerControl($container, $column, $record);
			case 'double':
			case 'decimal':
			case 'number':
				return $this->createFloatControl($container, $column, $record);
			case 'array':
			case 'object':
			case 'string':
			default:
				return $this->createDefaultControl($container, $column, $record);
		}
	}

	/**
	 * Returns the value from the input control.
	 *
	 * @param mixed $container the container control.
	 * @param \Prado\Data\Common\Mongo\TMongoFieldInfo $column the field metadata.
	 * @param mixed $record the active record instance.
	 * @return mixed the field value from the control.
	 */
	protected function getControlValue($container, $column, $record)
	{
		switch (strtolower($column->getBsonType())) {
			case 'date':
				return $this->getDateTimeValue($container, $column, $record);
			default:
				return $this->getDefaultControlValue($container, $column, $record);
		}
	}

	// -----------------------------------------------------------------------
	// Overrides for TMongoFieldInfo compatibility
	// -----------------------------------------------------------------------

	/**
	 * Returns whether the given field's input should be enabled for editing.
	 *
	 * The `_id` field is always disabled (it is auto-generated by MongoDB).
	 *
	 * @param \Prado\Data\Common\Mongo\TMongoFieldInfo $column the field metadata.
	 * @param mixed $record the active record instance.
	 * @return bool whether the control should be enabled.
	 */
	protected function getIsEnabled($column, $record)
	{
		return !($this->getParent()->getRecordPk() !== null && $column->getIsId());
	}

	/**
	 * Returns the current value of a field from the record, or an empty string
	 * if the record does not carry it.
	 *
	 * Unlike the SQL equivalent this does not consult a column default value, as
	 * MongoDB fields do not carry SQL-style defaults.
	 *
	 * @param \Prado\Data\Common\Mongo\TMongoFieldInfo $column the field metadata.
	 * @param mixed $record the active record instance.
	 * @return mixed the field value, or empty string.
	 */
	protected function getRecordPropertyValue($column, $record)
	{
		return $record->getColumnValue($column->getFieldName()) ?? '';
	}

	/**
	 * Creates a label for the field.
	 *
	 * Uses {@see \Prado\Data\Common\Mongo\TMongoFieldInfo::getFieldName} as the
	 * identifier, since MongoDB fields have no separate "column ID" concept.
	 *
	 * @param mixed $label the label control.
	 * @param \Prado\Data\Common\Mongo\TMongoFieldInfo $column the field metadata.
	 * @param mixed $record the active record instance.
	 */
	protected function createControlLabel($label, $column, $record)
	{
		$fieldname = ucwords(str_replace('_', ' ', $column->getFieldName())) . ':';
		$label->setText($fieldname);
		$label->setForControl(self::DEFAULT_ID);
	}

	// -----------------------------------------------------------------------
	// Control creation helpers
	// (Replicate TScaffoldInputCommon helpers without TDbTableColumn dependency)
	// -----------------------------------------------------------------------

	private function setDefaultProperty($container, $control, $column, $record): void
	{
		$control->setID(self::DEFAULT_ID);
		$control->setEnabled($this->getIsEnabled($column, $record));
		$container->Controls[] = $control;
	}

	private function setNotNullProperty($container, $control, $column, $record): void
	{
		$this->setDefaultProperty($container, $control, $column, $record);
		if ($column->getIsRequired() && !$column->getIsId()) {
			$this->createRequiredValidator($container, $column, $record);
		}
	}

	private function createBooleanControl($container, $column, $record)
	{
		$value = $this->getRecordPropertyValue($column, $record);
		$control = new TCheckBox();
		$control->setChecked(TPropertyValue::ensureBoolean($value));
		$control->setCssClass('boolean-checkbox');
		$this->setDefaultProperty($container, $control, $column, $record);
		return $control;
	}

	private function createDefaultControl($container, $column, $record)
	{
		$value = $this->getRecordPropertyValue($column, $record);
		$control = new TTextBox();
		$control->setText((string) $value);
		$control->setCssClass('default-textbox scaffold_input');
		$this->setNotNullProperty($container, $control, $column, $record);
		return $control;
	}

	private function createIntegerControl($container, $column, $record)
	{
		$control = $this->createDefaultControl($container, $column, $record);
		$val = $this->createTypeValidator($container, $column, $record);
		$val->setDataType(TValidationDataType::Integer);
		$val->setErrorMessage('Please enter an integer.');
		return $control;
	}

	private function createFloatControl($container, $column, $record)
	{
		$control = $this->createDefaultControl($container, $column, $record);
		$val = $this->createTypeValidator($container, $column, $record);
		$val->setDataType(TValidationDataType::Float);
		$val->setErrorMessage('Please enter a decimal number.');
		return $control;
	}

	private function createDateControl($container, $column, $record)
	{
		$value = $this->getRecordPropertyValue($column, $record);
		$control = new TDatePicker();
		$control->setFromYear(1900);
		$control->setInputMode(TDatePickerInputMode::DropDownList);
		$control->setDateFormat('yyyy-MM-dd');
		if (!empty($value)) {
			$control->setDate(substr((string) $value, 0, 10));
		}
		$control->setCssClass('date-dropdown');
		$this->setNotNullProperty($container, $control, $column, $record);
		return $control;
	}

	private function createDateTimeControl($container, $column, $record)
	{
		$value = $this->getRecordPropertyValue($column, $record);
		$dateControl = $this->createDateControl($container, $column, $record);
		$container->Controls[] = ' @ ';
		$time = $this->createTimeControl($container, $column, $record);
		if (!empty($value)) {
			$match = [];
			if (preg_match('/(\d+):(\d+):?(\d+)?/', substr((string) $value, 11), $match)) {
				$time[0]->setSelectedValue((int) ($match[1]));
				$time[1]->setSelectedValue((int) ($match[2]));
				if (isset($match[3])) {
					$time[2]->setSelectedValue((int) ($match[3]));
				}
			}
		}
		$time[0]->setID('scaffold_time_hour');
		return [$dateControl, $time[0], $time[1], $time[2]];
	}

	private function createTimeControl($container, $column, $record): array
	{
		$hours = [];
		for ($i = 0; $i < 24; $i++) {
			$hours[] = str_pad($i, 2, '0', STR_PAD_LEFT);
		}
		$mins = [];
		for ($i = 0; $i < 60; $i++) {
			$mins[] = str_pad($i, 2, '0', STR_PAD_LEFT);
		}

		$hcontrol = new \Prado\Web\UI\WebControls\TDropDownList();
		$hcontrol->setDataSource($hours);
		$hcontrol->setID(self::DEFAULT_ID);
		$hcontrol->dataBind();
		$hcontrol->setSelectedValue((int) (@date('H')));
		$container->Controls[] = $hcontrol;
		$container->Controls[] = ' : ';

		$mcontrol = new \Prado\Web\UI\WebControls\TDropDownList();
		$mcontrol->setDataSource($mins);
		$mcontrol->dataBind();
		$mcontrol->setID('scaffold_time_min');
		$mcontrol->setSelectedValue((int) (@date('i')));
		$container->Controls[] = $mcontrol;
		$container->Controls[] = ' : ';

		$scontrol = new \Prado\Web\UI\WebControls\TDropDownList();
		$scontrol->setDataSource($mins);
		$scontrol->dataBind();
		$scontrol->setID('scaffold_time_sec');
		$scontrol->setSelectedValue((int) (@date('s')));
		$container->Controls[] = $scontrol;

		return [$hcontrol, $mcontrol, $scontrol];
	}

	private function getDefaultControlValue($container, $column, $record)
	{
		$control = $container->findControl(self::DEFAULT_ID);
		if ($control instanceof TCheckBox) {
			return $control->getChecked();
		} elseif ($control instanceof TTextBox) {
			return $control->getText();
		} else {
			return '';
		}
	}

	private function getDateTimeValue($container, $column, $record): string
	{
		$date = $container->findControl(self::DEFAULT_ID)->getDate();
		$hour = $container->findControl('scaffold_time_hour')->getSelectedValue();
		$mins = $container->findControl('scaffold_time_min')->getSelectedValue();
		$secs = $container->findControl('scaffold_time_sec')->getSelectedValue();
		return "{$date} {$hour}:{$mins}:{$secs}";
	}

	private function createRequiredValidator($container, $column, $record)
	{
		$val = new TRequiredFieldValidator();
		$val->setErrorMessage('*');
		$val->setControlCssClass('required-input');
		$val->setCssClass('required');
		$val->setControlToValidate(self::DEFAULT_ID);
		$val->setValidationGroup($this->getParent()->getValidationGroup());
		$val->setDisplay(TValidatorDisplayStyle::Dynamic);
		$container->Controls[] = $val;
		return $val;
	}

	private function createTypeValidator($container, $column, $record)
	{
		$val = new TDataTypeValidator();
		$val->setControlCssClass('required-input2');
		$val->setCssClass('required');
		$val->setControlToValidate(self::DEFAULT_ID);
		$val->setValidationGroup($this->getParent()->getValidationGroup());
		$val->setDisplay(TValidatorDisplayStyle::Dynamic);
		$container->Controls[] = $val;
		return $val;
	}
}
