<?php

/**
 * TMongoCommandBuilder class file.
 *
 * @author Brad Anderson <belisoful@icloud.com>
 * @link https://github.com/pradosoft/prado
 * @license https://github.com/pradosoft/prado/blob/master/LICENSE
 */

namespace Prado\Data\Common\Mongo;

use Prado\Data\Common\IDataCommandBuilder;
use Prado\Data\IDataCommand;
use Prado\Data\TMongoCommand;
use Prado\Data\TMongoConnection;

/**
 * TMongoCommandBuilder generates preconfigured {@see TMongoCommand} objects for
 * common CRUD operations on a specific collection.
 *
 * It is the MongoDB analogue of {@see \Prado\Data\Common\TDbCommandBuilder} and
 * is used internally by {@see TMongoCollectionInfo} and
 * {@see \Prado\Data\DataGateway\TMongoCollectionGateway} to build commands without
 * repeating boilerplate.
 *
 * This class implements the canonical {@see IDataCommandBuilder} interface,
 * which is SQL-centric, by adapting each method to MongoDB semantics:
 *
 * - **$where** parameters (SQL WHERE clause strings) are accepted as MongoDB
 *   filter arrays. The sentinel value `'1=1'` (and any non-array string) is
 *   treated as an empty filter `[]`, meaning "match all documents".
 * - **$ordering** (column → 'asc'|'desc' pairs) are converted to MongoDB sort
 *   documents (field → 1|-1).
 * - **$limit / $offset** map directly to MongoDB's `limit` and `skip` options.
 * - **$select** (column list) maps to a MongoDB projection.
 * - **applyLimitOffset / applyOrdering** are no-ops that return their first
 *   argument unchanged, because MongoDB query options are not SQL strings.
 * - **bindColumnValues / bindArrayValues** are no-ops; MongoDB does not use
 *   bound parameters.
 * - **getLastInsertID** returns the last `_id` captured by an insert operation.
 *
 * @author Brad Anderson <belisoful@icloud.com>
 * @since 1.0.0
 */
class TMongoCommandBuilder extends \Prado\TComponent implements IDataCommandBuilder
{
	private TMongoConnection $_connection;
	private TMongoCollectionInfo $_collectionInfo;

	/** @var mixed The _id returned by the most recent insertOne operation. */
	private mixed $_lastInsertId = null;

	/**
	 * Constructor.
	 * @param TMongoConnection $connection the connection to execute commands on.
	 * @param TMongoCollectionInfo $collectionInfo metadata for the collection.
	 */
	public function __construct(TMongoConnection $connection, TMongoCollectionInfo $collectionInfo)
	{
		$this->_connection = $connection;
		$this->_collectionInfo = $collectionInfo;
		parent::__construct();
	}

	// -----------------------------------------------------------------------
	// IDataCommandBuilder — accessors
	// -----------------------------------------------------------------------

	/**
	 * @return TMongoConnection the connection this builder operates on.
	 */
	public function getDbConnection(): TMongoConnection
	{
		return $this->_connection;
	}

	/**
	 * @return TMongoCollectionInfo the collection metadata.
	 */
	public function getTableInfo(): TMongoCollectionInfo
	{
		return $this->_collectionInfo;
	}

	/**
	 * Returns the `_id` generated by the most recent {@see createInsertCommand}
	 * execution, or null if no insert has been performed yet.
	 *
	 * Unlike SQL sequence columns, MongoDB `_id` values are returned by the
	 * {@see TMongoCommand::insertOne} method directly. This accessor exposes
	 * the value from the last insert for code that inspects it via the builder.
	 *
	 * @return mixed the last inserted `_id`, or null.
	 */
	public function getLastInsertID(): mixed
	{
		return $this->_lastInsertId;
	}

	// -----------------------------------------------------------------------
	// IDataCommandBuilder — query-building helpers (SQL no-ops for MongoDB)
	// -----------------------------------------------------------------------

	/**
	 * No-op for MongoDB.
	 *
	 * SQL drivers append "LIMIT n OFFSET m" to a SQL string. MongoDB query
	 * options are not SQL strings, so this method returns `$sql` unchanged.
	 * Use {@see applyLimitSkip} to apply limits to a MongoDB options array.
	 *
	 * @param string $sql returned unchanged.
	 * @param int $limit ignored.
	 * @param int $offset ignored.
	 * @return string the original `$sql` value.
	 */
	public function applyLimitOffset($sql, $limit = -1, $offset = -1): string
	{
		return $sql;
	}

	/**
	 * No-op for MongoDB.
	 *
	 * SQL drivers append "ORDER BY col DIR" to a SQL string. MongoDB query
	 * options are not SQL strings, so this method returns `$sql` unchanged.
	 * Use {@see applySort} to apply sort to a MongoDB options array.
	 *
	 * @param string $sql returned unchanged.
	 * @param array $ordering ignored.
	 * @return string the original `$sql` value.
	 */
	public function applyOrdering($sql, $ordering): string
	{
		return $sql;
	}

	/**
	 * Builds a case-insensitive keyword search expression across the given fields.
	 *
	 * For MongoDB this returns a JSON-encoded `$or` filter rather than a SQL
	 * WHERE fragment. Use {@see getSearchFilter} to obtain the raw filter array.
	 *
	 * @param array $fields field names to search in.
	 * @param string $keywords space-separated search terms.
	 * @return string a JSON-encoded MongoDB `$or` filter, or '{}' if no terms/fields.
	 */
	public function getSearchExpression($fields, $keywords): string
	{
		$filter = $this->getSearchFilter((array) $fields, (string) $keywords);
		return $filter !== [] ? json_encode($filter) : '{}';
	}

	/**
	 * Returns the field names to include in a select/projection operation.
	 *
	 * @param mixed $data
	 *   - `'*'`  → `[]` (no projection; all fields returned).
	 *   - `null` → all known schema field names.
	 *   - `string` → comma-split field names.
	 *   - `array` → `array_keys($data)`.
	 * @return array field name strings.
	 */
	public function getSelectFieldList($data = '*'): array
	{
		if ($data === '*') {
			return [];
		}
		if ($data === null) {
			return $this->_collectionInfo->getFieldNames();
		}
		if (is_string($data)) {
			return array_values(array_filter(array_map('trim', explode(',', $data))));
		}
		if (is_array($data)) {
			return array_keys($data);
		}
		return [];
	}

	/**
	 * Builds and returns a find command configured with the given criteria.
	 *
	 * The `$sql` argument is interpreted as a MongoDB filter array for this
	 * implementation; non-array values resolve to an empty filter `[]`.
	 *
	 * @param mixed $sql treated as a MongoDB filter array.
	 * @param array $parameters merged into the filter when non-empty.
	 * @param array $ordering column → 'asc'|'desc' pairs; converted to MongoDB sort.
	 * @param int $limit negative means no limit.
	 * @param int $offset negative means no skip.
	 * @return IDataCommand a find command ready for execution.
	 */
	public function applyCriterias($sql, $parameters = [], $ordering = [], $limit = -1, $offset = -1): IDataCommand
	{
		return $this->createFindCommand($sql, $parameters, $ordering, $limit, $offset);
	}

	// -----------------------------------------------------------------------
	// IDataCommandBuilder — command factories
	// -----------------------------------------------------------------------

	/**
	 * Creates a find command for the collection.
	 *
	 * **MongoDB adaptation of the SQL interface:**
	 * - `$where` is a MongoDB filter array (or `'1=1'` / any non-array string
	 *   to match all documents).
	 * - `$parameters`, when non-empty, is merged into the filter via `array_merge`.
	 * - `$ordering` uses the PRADO convention `[field => 'asc'|'desc']` and is
	 *   converted to a MongoDB sort document `[field => 1|-1]`.
	 * - `$select` follows the same rules as {@see getSelectFieldList}.
	 *
	 * @param mixed $where MongoDB filter array, or '1=1' for no filter.
	 * @param array $parameters additional filter conditions to merge.
	 * @param array $ordering column → 'asc'|'desc' pairs.
	 * @param int $limit maximum documents; negative means no limit.
	 * @param int $offset documents to skip; negative means no skip.
	 * @param mixed $select field-list descriptor (see {@see getSelectFieldList}).
	 * @return IDataCommand
	 */
	public function createFindCommand($where = '1=1', $parameters = [], $ordering = [], $limit = -1, $offset = -1, $select = '*'): IDataCommand
	{
		$filter = $this->normalizeFilter($where, $parameters);
		$options = [];
		if (!empty($ordering)) {
			$this->applySort($options, $this->normalizeOrdering($ordering));
		}
		if ($limit > 0) {
			$options['limit'] = $limit;
		}
		if ($offset > 0) {
			$options['skip'] = $offset;
		}
		$this->applyProjection($options, $select);

		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setOptions($options)->setOperation(TMongoCommand::OP_FIND);
		return $cmd;
	}

	/**
	 * Creates a count command for the collection.
	 *
	 * **MongoDB adaptation:** `$where` is treated as a filter array (see
	 * {@see createFindCommand}). `$ordering`, `$limit`, and `$offset` are
	 * accepted for interface compatibility but are not applied to the count
	 * operation itself.
	 *
	 * @param mixed $where MongoDB filter array, or '1=1' for no filter.
	 * @param array $parameters additional filter conditions to merge.
	 * @param array $ordering ignored for count.
	 * @param int $limit ignored for count.
	 * @param int $offset ignored for count.
	 * @return IDataCommand
	 */
	public function createCountCommand($where = '1=1', $parameters = [], $ordering = [], $limit = -1, $offset = -1): IDataCommand
	{
		$filter = $this->normalizeFilter($where, $parameters);
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setOperation(TMongoCommand::OP_COUNT);
		return $cmd;
	}

	/**
	 * Creates an insertOne command for the collection.
	 *
	 * Executes a single-document insert. After calling `execute()` on the
	 * returned command, the generated `_id` can be retrieved via
	 * {@see getLastInsertID} (the command itself returns the `_id` directly
	 * from its `insertOne()` method, which bypasses this tracking).
	 *
	 * @param array $data field-name → value pairs for the document to insert.
	 * @return IDataCommand
	 */
	public function createInsertCommand($data): IDataCommand
	{
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setDocument((array) $data)->setOperation(TMongoCommand::OP_INSERT_ONE);
		return $cmd;
	}

	/**
	 * Creates an insert-or-ignore command for the collection.
	 *
	 * **MongoDB adaptation:** uses an upsert with `$setOnInsert` so the document
	 * is only written when it does not already exist (matched by `_id` if present,
	 * or by an empty filter otherwise). No fields are modified on an existing
	 * document.
	 *
	 * @param array $data the document to insert if absent.
	 * @return IDataCommand
	 */
	public function createInsertOrIgnoreCommand(array $data): IDataCommand
	{
		$filter = isset($data['_id']) ? ['_id' => $data['_id']] : [];
		$update = ['$setOnInsert' => $data];
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)
			->setUpdate($update)
			->setOptions(['upsert' => true])
			->setOperation(TMongoCommand::OP_UPDATE_ONE);
		return $cmd;
	}

	/**
	 * Creates an upsert command for the collection.
	 *
	 * **MongoDB adaptation:** performs an updateOne with `upsert = true`.
	 * The conflict filter is built from `$conflictColumns` (extracted from
	 * `$data`), or from `_id` when `$conflictColumns` is null.
	 * The update payload is `['$set' => $updateData ?? $data]` (excluding
	 * `_id` from the `$set` portion).
	 *
	 * @param array $data field-name → value pairs for the insert path.
	 * @param null|array $updateData fields to set on match; null means all
	 *   non-`_id` fields from `$data`.
	 * @param null|array $conflictColumns fields that form the match filter; null
	 *   means use `_id`.
	 * @return IDataCommand
	 */
	public function createUpsertCommand(array $data, ?array $updateData = null, ?array $conflictColumns = null): IDataCommand
	{
		// Build the match filter from conflict columns or _id.
		$filter = [];
		if ($conflictColumns !== null && $conflictColumns !== []) {
			foreach ($conflictColumns as $col) {
				if (array_key_exists($col, $data)) {
					$filter[$col] = $data[$col];
				}
			}
		} elseif (array_key_exists('_id', $data)) {
			$filter = ['_id' => $data['_id']];
		}

		// Build the $set payload, never including _id.
		$payload = $updateData ?? $data;
		unset($payload['_id']);

		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)
			->setUpdate(['$set' => $payload])
			->setOptions(['upsert' => true])
			->setOperation(TMongoCommand::OP_UPDATE_ONE);
		return $cmd;
	}

	/**
	 * Creates an updateMany command for the collection.
	 *
	 * **MongoDB adaptation:** `$where` is a filter array (see
	 * {@see createFindCommand}). `$data` becomes a `$set` update document.
	 *
	 * @param array $data field-name → new-value pairs.
	 * @param mixed $where MongoDB filter array, or '1=1' for all documents.
	 * @param array $parameters additional filter conditions to merge.
	 * @return IDataCommand
	 */
	public function createUpdateCommand($data, $where, $parameters = []): IDataCommand
	{
		$filter = $this->normalizeFilter($where, $parameters);
		$update = ['$set' => (array) $data];
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setUpdate($update)->setOperation(TMongoCommand::OP_UPDATE_MANY);
		return $cmd;
	}

	/**
	 * Creates a deleteMany command for the collection.
	 *
	 * **MongoDB adaptation:** `$where` is a filter array (see
	 * {@see createFindCommand}).
	 *
	 * @param mixed $where MongoDB filter array, or '1=1' for all documents.
	 * @param array $parameters additional filter conditions to merge.
	 * @return IDataCommand
	 */
	public function createDeleteCommand($where, $parameters = []): IDataCommand
	{
		$filter = $this->normalizeFilter($where, $parameters);
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setOperation(TMongoCommand::OP_DELETE_MANY);
		return $cmd;
	}

	/**
	 * Creates a bare command for the collection.
	 *
	 * The `$sql` argument is ignored (MongoDB has no SQL). The returned command
	 * targets this builder's collection with an empty filter and default OP_FIND
	 * operation; callers configure it further via the fluent builder API.
	 *
	 * @param mixed $sql ignored.
	 * @return IDataCommand
	 */
	public function createCommand($sql): IDataCommand
	{
		return $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
	}

	/**
	 * No-op for MongoDB.
	 *
	 * SQL drivers bind typed column values into a prepared statement.
	 * MongoDB does not use bound parameters.
	 *
	 * @param IDataCommand $command ignored.
	 * @param array $values ignored.
	 */
	public function bindColumnValues($command, $values): void
	{
		// No-op: MongoDB commands do not use bound parameters.
	}

	/**
	 * No-op for MongoDB.
	 *
	 * SQL drivers bind positional or named parameter arrays into a prepared
	 * statement. MongoDB does not use bound parameters.
	 *
	 * @param IDataCommand $command ignored.
	 * @param array $values ignored.
	 */
	public function bindArrayValues($command, $values): void
	{
		// No-op: MongoDB commands do not use bound parameters.
	}

	// -----------------------------------------------------------------------
	// MongoDB-specific helpers (public, not part of IDataCommandBuilder)
	// -----------------------------------------------------------------------

	/**
	 * Applies limit and skip values to a query options array in-place.
	 * @param array $options query options to modify.
	 * @param int $limit maximum documents to return; 0 or negative means no limit.
	 * @param int $skip documents to skip; 0 or negative means no skip.
	 */
	public function applyLimitSkip(array &$options, int $limit, int $skip): void
	{
		if ($limit > 0) {
			$options['limit'] = $limit;
		}
		if ($skip > 0) {
			$options['skip'] = $skip;
		}
	}

	/**
	 * Applies a sort document to a query options array in-place.
	 * @param array $options query options to modify.
	 * @param array $sort sort document, e.g. `['name' => 1, 'createdAt' => -1]`.
	 */
	public function applySort(array &$options, array $sort): void
	{
		if ($sort !== []) {
			$options['sort'] = $sort;
		}
	}

	/**
	 * Applies a field projection to a query options array in-place.
	 *
	 * @param array $options query options to modify.
	 * @param mixed $fields
	 *   - `null`  → project all known schema fields as an inclusion projection.
	 *   - `'*'`   → no projection (all fields, MongoDB default).
	 *   - `array` → used verbatim as the projection document.
	 *   - `string` (comma-separated) → converted to an inclusion projection.
	 */
	public function applyProjection(array &$options, mixed $fields): void
	{
		if ($fields === '*' || $fields === []) {
			return;
		}
		if ($fields === null) {
			$knownFields = $this->_collectionInfo->getFieldNames();
			if ($knownFields !== []) {
				$options['projection'] = array_fill_keys($knownFields, 1);
			}
			return;
		}
		if (is_array($fields)) {
			$options['projection'] = $fields;
			return;
		}
		if (is_string($fields)) {
			$list = array_values(array_filter(array_map('trim', explode(',', $fields))));
			if ($list !== []) {
				$options['projection'] = array_fill_keys($list, 1);
			}
		}
	}

	/**
	 * Builds a MongoDB `$or` filter that performs a case-insensitive regex search
	 * across the given fields for each keyword.
	 *
	 * Equivalent to {@see TDbCommandBuilder::getSearchExpression} for MongoDB.
	 *
	 * @param array $fields field names to search.
	 * @param string $keywords space-separated search terms.
	 * @return array a MongoDB filter document, or `[]` if no terms or fields.
	 */
	public function getSearchFilter(array $fields, string $keywords): array
	{
		$words = array_filter(preg_split('/\s+/', trim($keywords)));
		if ($words === [] || $fields === []) {
			return [];
		}
		$conditions = [];
		foreach ($fields as $field) {
			foreach ($words as $word) {
				$conditions[] = [
					$field => [
						'$regex' => preg_quote((string) $word, '/'),
						'$options' => 'i',
					],
				];
			}
		}
		return ['$or' => $conditions];
	}

	/**
	 * Creates a find command using MongoDB-native arguments (filter array + options array).
	 *
	 * This is a convenience method for code that works directly with MongoDB
	 * filter/options documents rather than the SQL-centric {@see createFindCommand}.
	 *
	 * @param array $filter MongoDB filter document.
	 * @param array $options MongoDB query options (sort, limit, skip, projection, …).
	 * @return IDataCommand
	 */
	public function createFindCommandMongo(array $filter = [], array $options = []): IDataCommand
	{
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setOptions($options)->setOperation(TMongoCommand::OP_FIND);
		return $cmd;
	}

	/**
	 * Creates an insertOne command using a MongoDB-native document array.
	 * @param array $document the document to insert.
	 * @return IDataCommand
	 */
	public function createInsertOneCommand(array $document): IDataCommand
	{
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setDocument($document)->setOperation(TMongoCommand::OP_INSERT_ONE);
		return $cmd;
	}

	/**
	 * Creates an insertMany command using an array of MongoDB-native document arrays.
	 * @param array $documents the documents to insert.
	 * @return IDataCommand
	 */
	public function createInsertManyCommand(array $documents): IDataCommand
	{
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setDocuments($documents)->setOperation(TMongoCommand::OP_INSERT_MANY);
		return $cmd;
	}

	/**
	 * Creates an updateOne command using MongoDB-native filter and update documents.
	 * @param array $filter query filter.
	 * @param array $update update specification.
	 * @param array $options additional options (e.g. `['upsert' => true]`).
	 * @return IDataCommand
	 */
	public function createUpdateOneCommand(array $filter, array $update, array $options = []): IDataCommand
	{
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setUpdate($update)->setOptions($options)->setOperation(TMongoCommand::OP_UPDATE_ONE);
		return $cmd;
	}

	/**
	 * Creates an updateMany command using MongoDB-native filter and update documents.
	 * @param array $filter query filter.
	 * @param array $update update specification.
	 * @param array $options additional options.
	 * @return IDataCommand
	 */
	public function createUpdateManyCommand(array $filter, array $update, array $options = []): IDataCommand
	{
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setUpdate($update)->setOptions($options)->setOperation(TMongoCommand::OP_UPDATE_MANY);
		return $cmd;
	}

	/**
	 * Creates a deleteOne command using a MongoDB-native filter.
	 * @param array $filter query filter.
	 * @return IDataCommand
	 */
	public function createDeleteOneCommand(array $filter): IDataCommand
	{
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setOperation(TMongoCommand::OP_DELETE_ONE);
		return $cmd;
	}

	/**
	 * Creates a deleteMany command using a MongoDB-native filter.
	 * @param array $filter query filter.
	 * @return IDataCommand
	 */
	public function createDeleteManyCommand(array $filter): IDataCommand
	{
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setOperation(TMongoCommand::OP_DELETE_MANY);
		return $cmd;
	}

	/**
	 * Creates a count command using a MongoDB-native filter.
	 * @param array $filter query filter.
	 * @return IDataCommand
	 */
	public function createCountCommandMongo(array $filter = []): IDataCommand
	{
		$cmd = $this->_connection->createCommand($this->_collectionInfo->getCollectionName());
		$cmd->setFilter($filter)->setOperation(TMongoCommand::OP_COUNT);
		return $cmd;
	}

	// -----------------------------------------------------------------------
	// Internal helpers
	// -----------------------------------------------------------------------

	/**
	 * Normalises a `$where` argument from the SQL-centric interface into a
	 * MongoDB filter array.
	 *
	 * - Arrays are used as-is, optionally merged with `$parameters`.
	 * - Non-array strings (including the SQL sentinel `'1=1'`) resolve to `[]`.
	 *
	 * @param mixed $where the filter argument.
	 * @param array $parameters additional conditions to merge.
	 * @return array the MongoDB filter document.
	 */
	protected function normalizeFilter(mixed $where, array $parameters = []): array
	{
		$filter = is_array($where) ? $where : [];
		if ($parameters !== []) {
			$filter = array_merge($filter, $parameters);
		}
		return $filter;
	}

	/**
	 * Converts a PRADO ordering array (`[field => 'asc'|'desc']`) to a
	 * MongoDB sort document (`[field => 1|-1]`).
	 *
	 * @param array $ordering PRADO-style ordering.
	 * @return array MongoDB sort document.
	 */
	protected function normalizeOrdering(array $ordering): array
	{
		$sort = [];
		foreach ($ordering as $field => $direction) {
			$sort[$field] = (strtolower((string) $direction) === 'asc') ? 1 : -1;
		}
		return $sort;
	}
}
